STATUS_ACTIVE = "ACTIVE"
STATUS_DISOWNED = "DISOWNED"

GSI1_NAME = "GSI1"
GSI1_PK_DISOWNED = "DISOWNED"

ENV_SRC_BUCKET = "SRC_BUCKET_NAME"
ENV_DST_BUCKET = "DST_BUCKET_NAME"
ENV_TABLE_NAME = "TABLE_NAME"
ENV_MAX_COPIES = "MAX_COPIES"
ENV_THRESHOLD_SECONDS = "DISOWNED_THRESHOLD_SECONDS"